applications:
  - name: ChatGPT
    comment: Web application for ChatGPT
    url: https://chat.openai.com
    icon: chatgpt.png
  - name: Gmail
    comment: Web application for Gmail
    url: https://mail.google.com
    icon: gmail.png
  - name: Outlook
    comment: Web application for Microsoft Outlook
    url: https://outlook.office.com
    icon: outlook.png

input_path_icons: ./icons
output_path_icons: ./out.icons
output_path_desktop_entries: ./out.desktop-entries
